Congrats mail cron
wolox-training/mm-express-js pull request #20
Opened 2020-06-01 20:07 UTC by mnmallea

## Summary
- Added cron to send congratulation mails.
- Runs every day at 0:00. Por qué? No hay por qué.
- Added specs.

## Known Issues
None.

## Trello Card
https://trello.com/c/SPsRNlLI/39-proceso-de-env%C3%ADo-de-mail-de-felicitaci%C3%B3n

2020-06-09 15:15 UTC, lnmedrano requested changes

2020-06-09 15:15 UTC, lnmedrano commented on app/services/mailer.js
> +    text: `Hola ${user.firstName}. Tu cuenta ha sido creada correctamente en Weeter`
Messages are usually set in env vars. That way, if we see a typo ('bienvendio'), or we want to change the message, we can change the env and re-deploy, without having to go through the entire pr proccess.

2020-06-09 15:15 UTC, lnmedrano commented on app/services/mailer.js
> +    `
Idem with messages

2020-06-09 15:15 UTC, lnmedrano commented on app/services/users.js
> +
Is this used?

2020-06-09 15:15 UTC, lnmedrano commented on app/services/users.js
> +    ],
Nice :sunglasses:

2020-06-09 16:11 UTC, mnmallea commented on app/services/users.js
> +
no, f

2020-06-11 17:15 UTC, lnmedrano approved these changes

2020-06-12 14:38 UTC, merged